version: 2

references:
  workspace: &workspace
    ~/workspace
  cache_key: &cache_key
    jars-{{ checksum "build.gradle" }}-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}

jobs:
  build:
    working_directory: *workspace
    docker:
      - image: circleci/android:api-28-alpha
    environment:
      TERM: dumb
      GRADLE_OPTS: '-Dorg.gradle.daemon=false'
    steps:
      - checkout
      - restore_cache:
          key: *cache_key
      - run:
          name: Assemble
          command: ./gradlew -p dexopener assembleAndroidTest
      - run:
          name: Run Lint and Tests
          command: ./gradlew -p dexopener lintDebug jacocoTestDebugUnitTestReport
      - save_cache:
          key: *cache_key
          paths:
            - ~/.gradle/caches
            - ~/.gradle/wrapper
      - store_artifacts:
          path: dexopener/build/reports
      - store_test_results:
          path: dexopener/build/test-results
      - persist_to_workspace:
          root: .
          paths:
            - ftl
            - dexopener/build
  test_instrumented:
    working_directory: *workspace
    docker:
      - image: google/cloud-sdk:latest
    environment:
      TERM: dumb
    steps:
      - attach_workspace:
          at: *workspace
      - run:
          name: Authenticate to GCP
          command: ftl/auth.sh dexopener
      - run:
          name: Run tests on Firebase Test Lab
          command: ftl/test.sh dexopener/build/outputs/apk/androidTest/debug/dexopener-debug-androidTest.apk
      - run:
          name: Fetch test results
          command: ftl/fetch_results.sh test-lab-52rkbqmf6t0pc-itz864dzcxk5x dexopener/build/test-results/ftl
      - store_artifacts:
          path: dexopener/build/test-results/ftl
      - store_test_results:
          path: dexopener/build/test-results/ftl

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test_instrumented:
          requires:
            - build
